on:
  push:
    branches:
      - main
      - release-pages
  release:
    types: [published, edited, deleted, unpublished]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  feishu-pages:
    name: Publish Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: dist/.cache
          key: cache-dist

      - name: Exporting
        env:
          FEISHU_ENDPOINT: 'https://open.larksuite.com/'
          FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
          FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
          FEISHU_SPACE_ID: '7338695984207101957'
          OUTPUT_DIR: ./dist
          BASE_URL: https://tsui66.github.io/tech-stack-fo-global-startups/
        uses: longbridgeapp/feishu-pages@main
      - name: Build Website
        run: |
          cp -r dist/docs/* website/docs/
          cp dist/docs.json website/
          yarn
          yarn workspace website generate-releases
          yarn workspace website build
          yarn autocorrect --fix website/
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './website/.vitepress/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
